# These are supported funding model platforms

custom: ['https://axcora.com/getaxcoracms','https://www.fiverr.com/creativitas/create-your-website-with-cms','https://www.fiverr.com/creativitas/design-your-modern-website-using-jekyll']
