# These are supported funding model platforms

custom: ['https://www.fiverr.com/creativitas/create-your-website-with-cms','https://www.fiverr.com/creativitas/design-your-modern-website-using-jekyll','https://www.fiverr.com/creativitas/create-your-custom-website-and-app']
